version: '3.8'

services:
  projectb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: projectb-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - projectb-network

networks:
  projectb-network:
    driver: bridge
