[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['npm install --legacy-peer-deps']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'chmod +x start.sh && ./start.sh'

[variables]
NODE_ENV = 'production'
PORT = '3000'
HOSTNAME = '0.0.0.0'
